### PR TITLE
Update the account to a non generalized one

### PR DESCRIPTION
**Pull request by maptuhec**

### CODE REVIEW

**Comment by sadiqevani** [comment]
@maptuhec a bit more details on this?

**Comment by sadiqevani** [comment]
If you @maptuhec @alekseytsekov want to contribute to this project, please (emphasise on the `please`) do it in a meaningful way. Changing and renaming variables its not work and does not push this project forward.

Also, please continuing forward, provide explanation of the work you're doing in this project, and for what reason you think the changes you're doing impact the project in a meaningful way.

### I will not approve anything that is not relevant to the project, and does not push the project forward.

**Comment by maptuhec** [comment]
Hey @sadiqevani  you can find more information about the request here:
https://forum.aeternity.com/t/playground-ide-transaction-build-error-ownerid-field-is-required/3680/12

If you don't find that the project is not currently working meaningful, please let me know. If more detailed explanation about the issue is needed, don't hesitate to ask me here, in the forum or in private message.

Thanks,
Martin

**Comment by sadiqevani** [comment]
> Hey @sadiqevani you can find more information about the request here:
> https://forum.aeternity.com/t/playground-ide-transaction-build-error-ownerid-field-is-required/3680/12
> 
> If you don't find that the project is not currently working meaningful, please let me know. If more detailed explanation about the issue is needed, don't hesitate to ask me here, in the forum or in private message.
> 
> Thanks,
> Martin

Understood. I'll proceed and merge this.

Thank you for the prompt answer.

Cheers.
Sadi

**Pull request merged**
