### PR TITLE
Playground new release 16.07.09

### PR DESCRIPTION
**Pull request by maptuhec**
The new release will include:
* The provided account is changed with a non generalized one
* Verification of transaction is added, which first verifies the transaction before sending it to the blockchain.
* Packages upgrades
* Documentation updates

### CODE REVIEW

**Comment by sadiqevani** [comment]
@maptuhec can we postpone the release for later today, I have some other changes and testing that I wanna do.

**Comment by maptuhec** [comment]
@sadiqevani of course, feel free to work with Shubhendu for the release, whenever you are ready.

**Comment by sadiqevani** [comment]
@maptuhec lets hold of the release for the end of this week, I'm testing playground and there's a few issues.

- Bytecode is not being displayed on the right sidebar of the editor.
- Compilation works, but deployment returns some errors.

I think it has to do with the upgrades in the SDK. Might take me a while to fix everything.

**Comment by maptuhec** [comment]
@sadiqevani  the byte code is not returned because the contract is not deployed. The issue is probably not in the sdk, because we haven't updated the SDK version and the prod application is working. If you need help, we can help for faster release

**Comment by sadiqevani** [comment]
@maptuhec 
> he byte code is not returned because the contract is not deployed.

I'll be checking this tomorrow.

> The issue is probably not in the sdk, because we haven't updated the SDK version and the prod application is working.

I need to refresh my memory on the things that I've done on playground, and to get back into the zone and start working on the new features.

Thank you though, I'll clean up some issues and see where you guys can help.

**Comment by maptuhec** [comment]
@sadiqevani  Today the hosted compiler which the playground is using will also be updated, so the example contract which is provided by the playground will also not work. FYI

**Comment by sadiqevani** [comment]
@maptuhec Do you have any other example where I can find a new template, so it fixes the issue?

**Comment by maptuhec** [comment]
@sadiqevani yes, here : https://forum.aeternity.com/t/hosted-compiler-july-scheduled-update/3937

**Comment by maptuhec** [comment]
@sadiqevani any progress here?

**Comment by maptuhec** [comment]
@sadiqevani what is the status of the release?

**Comment by sadiqevani** [comment]
Hey @maptuhec I am on vacation until 1st of august.

**Comment by maptuhec** [comment]
@sadiqevani  so I will try to fix the issues and release new version with minor changes, because the app is not working and we can't keep it for one more week like that. I will keep you upto date.

**Comment by sadiqevani** [comment]
@maptuhec Yep. Go ahead. And sorry.

**Comment by maptuhec** [comment]
I will close this since it is outdated

**Pull request closed without merging**
